### ISSUE TITLE
Incorrect shared_buffers suggestion

### ISSUE THREAD

**Issue by zam6ak** [sebastianwebber/pgconfig#10]
The app is not taking OS into consideration it seems.

It suggest that I use 4GB for `shared_buffers` for a system with 16 GB of memory (total size of memory is 32 GB but I am 'giving' half to PG)...With that scenario it says 4 GB

Then in the documentation it says this:
https://www.postgresql.org/docs/current/static/runtime-config-resource.html

> Also, on Windows, large values for shared_buffers aren't as effective. You may find better results keeping the setting relatively low and using the operating system cache more instead. The useful range for shared_buffers on Windows systems is generally from 64MB to 512MB.

**Comment by zam6ak** [comment]
Here is the output from pgconfig and another app that takes OS into consideration.
**Look at the difference between shared_buffers, work_mem, and checkpoint configs!!!**

- based on 16 GB of memory
- PG v 9.4
- 100 connections
- Web Application profile


```
# Generated by PGConfig 2.0 beta
## http://pgconfig.org

# Memory Configuration
shared_buffers = 4GB
effective_cache_size = 12GB
work_mem = 164MB
maintenance_work_mem = 1GB

# Checkpoint Related Configuration
checkpoint_segments = 32
checkpoint_completion_target = 0.7
wal_buffers = 16MB

# Network Related Configuration
listen_addresses = '*'
max_connections = 100

```

http://pgtune.leopard.in.ua/
OS: windows
```
max_connections = 100
shared_buffers = 512MB
effective_cache_size = 12GB
work_mem = 54176kB
maintenance_work_mem = 1GB
checkpoint_segments = 32
checkpoint_completion_target = 0.7
wal_buffers = 16MB
default_statistics_target = 100

```

**Comment by sebastianwebber** [comment]
@zam6ak thanks for the report.

I Will work on that today.

Please wait for my update.

**Comment by zam6ak** [comment]
When you go to export the config, for Windows, it is still ignoring 512 MB option...

**Comment by sebastianwebber** [comment]
@zam6ak when i took Windows for the OS, all shared_buffers values are limited to 512MB.

Take a look:
https://www.pgconfig.org/#/tuning?total_ram=10&max_connections=100&enviroment_name=WEB&pg_version=9.6&os_type=Windows&arch=x86-64&share_link=true

Can you send tell me which parameters are you using? Perhaps a shared url?

Thanks.

**Comment by zam6ak** [comment]
@sebastianwebber  the issue is when you go to EXPORT
The value is `ALTER SYSTEM SET shared_buffers TO '2GB';` 

Try to export using the same link you sent...
