### ISSUE TITLE
PostgreSQL 10 support

### ISSUE THREAD

**Issue by avelino** [sebastianwebber/pgconfig#13]

**Comment by qdbdbp** [comment]
Are you already working on support for PostgreSQL 10?

**Comment by avelino** [comment]
I did not report that you need support

**Comment by sebastianwebber** [comment]
@avelino and @qdbdbp:

Currently, I'm working on a new api which provides support for PostgreSQL 10.

I plan to finish and deploy a beta version this weekend.

[]'s

**Comment by sebastianwebber** [comment]
pg 10 support added
