### ISSUE TITLE
Pressing 'Run it now' doesnt do anything

### ISSUE THREAD

**Issue by danger89** [sebastianwebber/pgconfig#15]
Hi Sebastian,

When I try to press the _Run it now!_ button, both Firefox and Chrome doesn't do anything..

I would expect to get the configs.

Kind regards,
Melroy van den Berg
Pre-Alpha/Beta-tester of PGConfig 😃

**Comment by sebastianwebber** [comment]
hey @danger89 thanks for your feedback.

I make a serious mistake on the configuration of the api on google cloud and all of my credits ended. =/

I took the oportunity to migrate the api to digital ocean cloud.

When the DNS propagates, all must be fine.

Let me know any problem.

Once again, thanks.
