### ISSUE TITLE
Different config values between API and WEB

### ISSUE THREAD

**Issue by fabriziomello** [sebastianwebber/pgconfig#2]
Using the API I got:

$ curl -X GET http://api.pgconfig.org/v1/tuning/get-config\?enviroment_name\=WEB\&total_ram\=7GB\&max_connections\=1000\&format\=alter_system
-- Memory Configuration
ALTER SYSTEM SET shared_buffers TO '1.75GB';
ALTER SYSTEM SET effective_cache_size TO '5.25GB';
ALTER SYSTEM SET work_mem TO '7.17MB';
ALTER SYSTEM SET maintenance_work_mem TO '448.00MB';

-- Checkpoint Related Configuration
ALTER SYSTEM SET min_wal_size TO '512.00MB';
ALTER SYSTEM SET max_wal_size TO '1.50GB';
ALTER SYSTEM SET checkpoint_completion_target TO '0.7';
ALTER SYSTEM SET wal_buffers TO '53.76MB';

And using the WEB interface I got:
-- Generated by PGConfig 1.55
-- Using 'WEB' profile

ALTER SYSTEM SET wal_buffers TO '16MB';
ALTER SYSTEM SET checkpoint_completion_target TO '0.7';
ALTER SYSTEM SET max_wal_size TO '2GB';
ALTER SYSTEM SET min_wal_size TO '512MB';
ALTER SYSTEM SET maintenance_work_mem TO '448MB';
ALTER SYSTEM SET work_mem TO '7MB';
ALTER SYSTEM SET effective_cache_size TO '5GB';
ALTER SYSTEM SET shared_buffers TO '2GB';

-- Connection stuff
ALTER SYSTEM SET max_connections TO 1000;
ALTER SYSTEM SET listen_addresses TO '*';

**Comment by sebastianwebber** [comment]
api fixed. thanks @fabriziomello
