### ISSUE TITLE
make the old version available if possible?

### ISSUE THREAD

**Issue by zam6ak** [sebastianwebber/pgconfig#5]
The new UI requires way too much clicking to get to ALTER commands.
Old one was much better IMHO - any way you can make it available...

Or change new UI where everything is on one page - just a suggestion

**Comment by sebastianwebber** [comment]
Hi @zam6ak,

You can connect to the old UI on the follow URL:
http://pgconfig-swebber.rhcloud.com/

About the clicks, do you tried using `curl` and call directly the API like this?
```bash
$ curl -X GET http://api.pgconfig.org/v1/tuning/get-config\?enviroment_name\=WEB\&total_ram\=7GB\&max_connections\=1000\&format\=alter_system
```
... and the output:

```sql
-- Memory Configuration
ALTER SYSTEM SET shared_buffers TO '2GB';
ALTER SYSTEM SET effective_cache_size TO '5GB';
ALTER SYSTEM SET work_mem TO '7MB';
ALTER SYSTEM SET maintenance_work_mem TO '448MB';

-- Checkpoint Related Configuration
ALTER SYSTEM SET min_wal_size TO '512MB';
ALTER SYSTEM SET max_wal_size TO '2GB';
ALTER SYSTEM SET checkpoint_completion_target TO '0.7';
ALTER SYSTEM SET wal_buffers TO '16MB';

-- Network Related Configuration
ALTER SYSTEM SET listen_addresses TO '*';
ALTER SYSTEM SET max_connections TO '1000';
```

Do you have any suggestions where i can put help about it on the new ui?

**Comment by zam6ak** [comment]
I agree curl is handy for scripting but using the website via bookmark is way more convenient especially when curl is not easily available (e.g. on mobile devices)

In my opinion, learning about different options and what they mean is really nice, but not so important once you learn their meaning and just want to use the tool :)

Again, thanks for the tool. Quite nice

BTW, the url for the old tool seems unavailable...

**Comment by sebastianwebber** [comment]
@zam6ak took a lot of work, but i bring back some features of the old interface.

Can you take a look and send me a feedback?

**Comment by zam6ak** [comment]
@sebastianwebber Nice! Much better. Thanks!
