### ISSUE TITLE
log_connections duplicated

### ISSUE THREAD

**Issue by zam6ak** [sebastianwebber/pgconfig#9]
When you go to export commands or settings file the log_connections param is duplicated:

```
ALTER SYSTEM SET log_connections TO 'on';
ALTER SYSTEM SET log_connections TO 'on';
```

**Comment by sebastianwebber** [comment]
fixed on https://github.com/sebastianwebber/pgconfig-api/commit/4a97b0b2bd86177184710d2585285e7f840cef16.
